# Generated by Django 5.1 on 2024-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=3)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('name_of_company', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_listing', models.DateField(blank=True, null=True)),
                ('paid_up_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_lot', models.IntegerField(blank=True, null=True)),
                ('isin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_code', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('security_id', models.CharField(blank=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_new_name', models.CharField(blank=True, max_length=255, null=True)),
                ('igroup_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isubgroup_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
