# Generated by Django 5.1 on 2024-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algomitra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='igroup_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry_new_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issuer_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='isubgroup_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_exchange',
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_of_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
