# Generated by Django 5.1 on 2024-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algomitra_app', '0002_remove_stock_group_remove_stock_igroup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.AddField(
            model_name='stock',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='igroup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry_new_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='instrument',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isubgroup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='security_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='security_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='security_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_of_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
