# Generated by Django 5.1 on 2024-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algomitra_app', '0003_remove_stock_exchange_stock_group_stock_igroup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_of_listing',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='face_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='igroup_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry_new_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='isin_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issuer_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='isubgroup_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_lot',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='paid_up_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='security_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='series',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_exchange',
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_of_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
