# Generated by Django 5.1 on 2024-09-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algomitra_app', '0004_remove_stock_date_of_listing_remove_stock_face_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='industry',
            new_name='Token',
        ),
    ]
