# Generated by Django 5.1 on 2024-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algomitra_app', '0005_rename_industry_stock_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Token',
        ),
        migrations.AddField(
            model_name='stock',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
